from app.models.raw_materials import RawMaterial
from app.models.paper_roll import PaperRoll
from app.models.adhesives_glue import AdhesivesGlue
from app.models.stitching_material import StitchingMaterial
from app.models.chemicals import Chemicals
from app.models.packaging import Packaging
from app.models.ink_and_solvents import InksandSolvents
from app.models.production_components import ProductionComponents
from app.models.employee import Employee
from app.models.employee_department import EmployeeDepartment
from app.models.department import Department
from app.models.client import ClientAccount
from app.models.american_box import AmericanBox
from app.models.sheet_carton import SheetCarton
from app.models.rolls import Rolls
from app.models.flut import Flut 
from app.models.job_order import JobOrder
from app.models.job_order_item import JobOrderItem
from app.models.gsm import Gsm
from app.models.paper_type import PaperType
from app.models.client_job_orders import ClientJobOrder
from app.models.router_access import RouterAccess
from app.models.job_order_flut_rolls import JobOrderFlutRoll
from app.models.tape import Tape
