"""add tape table

Revision ID: 1a80b04b01ba
Revises: 1d509618eaa0
Create Date: 2025-09-01 17:17:39.087975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a80b04b01ba'
down_revision: Union[str, Sequence[str], None] = '1d509618eaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('size_raw', sa.String(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('thickness', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('roll_number', sa.String(), nullable=True),
    sa.Column('made_in', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tape_id'), 'tape', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tape_id'), table_name='tape')
    op.drop_table('tape')
    # ### end Alembic commands ###
