"""changing constraints

Revision ID: 1d509618eaa0
Revises: d12c2b4a08aa
Create Date: 2025-08-31 17:56:23.838067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d509618eaa0'
down_revision: Union[str, Sequence[str], None] = 'd12c2b4a08aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_order_flut_rolls', 'job_order_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_order_flut_rolls', 'flut_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_order_flut_rolls', 'paper_roll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_order_flut_rolls', 'allocated_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_order_flut_rolls', 'allocated_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('job_order_flut_rolls', 'paper_roll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_order_flut_rolls', 'flut_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_order_flut_rolls', 'job_order_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
