"""init schema

Revision ID: 8693451ea11b
Revises: 
Create Date: 2025-08-31 13:33:24.462001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8693451ea11b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_order_flut_rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_order_item_id', sa.Integer(), nullable=False),
    sa.Column('flut_id', sa.Integer(), nullable=False),
    sa.Column('paper_roll_id', sa.Integer(), nullable=False),
    sa.Column('allocated_width', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flut_id'], ['flut.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_order_item_id'], ['job_order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_roll_id'], ['paper_rolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_order_flut_rolls_id'), 'job_order_flut_rolls', ['id'], unique=False)
    op.drop_table('job_order_paper_rolls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_order_paper_rolls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_roll_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allocated_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_order_id'], ['job_orders.id'], name=op.f('job_order_paper_rolls_job_order_id_fkey')),
    sa.ForeignKeyConstraint(['paper_roll_id'], ['paper_rolls.id'], name=op.f('job_order_paper_rolls_paper_roll_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_order_paper_rolls_pkey'))
    )
    op.drop_index(op.f('ix_job_order_flut_rolls_id'), table_name='job_order_flut_rolls')
    op.drop_table('job_order_flut_rolls')
    # ### end Alembic commands ###
