"""add calculated weight to the job order flut roll

Revision ID: d12c2b4a08aa
Revises: 8693451ea11b
Create Date: 2025-08-31 17:53:42.036175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12c2b4a08aa'
down_revision: Union[str, Sequence[str], None] = '8693451ea11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_order_flut_rolls', sa.Column('calculated_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_order_flut_rolls', 'calculated_weight')
    # ### end Alembic commands ###
