-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.adhesives_glue
(
    id serial NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    weight double precision NOT NULL,
    cost double precision,
    received_at timestamp without time zone DEFAULT now(),
    CONSTRAINT adhesives_glue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chemicals
(
    id serial NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    weight double precision NOT NULL,
    quantity integer NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    cost double precision,
    received_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT chemicals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    no_of_managers integer DEFAULT 0,
    CONSTRAINT department_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    serial_number character varying COLLATE pg_catalog."default",
    CONSTRAINT employee_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee_department
(
    id serial NOT NULL,
    employee_id integer,
    department_id integer,
    CONSTRAINT employee_department_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inks_and_solvents
(
    id serial NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    weight integer NOT NULL,
    quantity integer NOT NULL,
    color character varying COLLATE pg_catalog."default" NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    cost integer,
    color_code character varying COLLATE pg_catalog."default" NOT NULL,
    received_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT inks_and_solvents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.packaging
(
    id serial NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    weight double precision NOT NULL,
    quantity integer NOT NULL,
    dimensions double precision NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    cost double precision,
    received_at timestamp without time zone DEFAULT now(),
    CONSTRAINT packaging_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.paper_rolls
(
    id serial NOT NULL,
    raw_id integer NOT NULL,
    roll_id integer NOT NULL,
    paper_type character varying COLLATE pg_catalog."default" NOT NULL,
    gsm double precision NOT NULL,
    roll_width double precision NOT NULL,
    job_order_id integer,
    serial_number character varying COLLATE pg_catalog."default" NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'available'::character varying,
    degree character varying COLLATE pg_catalog."default",
    CONSTRAINT paper_rolls_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.production_component
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    component character varying COLLATE pg_catalog."default" NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    weight double precision NOT NULL,
    color character varying COLLATE pg_catalog."default",
    color_code character varying COLLATE pg_catalog."default",
    updated_at timestamp without time zone,
    dimensions double precision DEFAULT 0.0,
    CONSTRAINT production_component_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.raw_material
(
    id serial NOT NULL,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    degree character varying COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    paper_type character varying COLLATE pg_catalog."default" NOT NULL,
    roll_width double precision NOT NULL,
    gsm double precision NOT NULL,
    color character varying COLLATE pg_catalog."default" NOT NULL,
    received_at timestamp without time zone,
    job_order_id integer NOT NULL,
    cost double precision,
    serial_number character varying COLLATE pg_catalog."default",
    CONSTRAINT raw_material_pkey PRIMARY KEY (id),
    CONSTRAINT raw_material_serial_number_key UNIQUE (serial_number)
);

CREATE TABLE IF NOT EXISTS public.router_access
(
    id serial NOT NULL,
    department_id integer,
    resource_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT router_access_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stitching_material
(
    id serial NOT NULL,
    material_name character varying COLLATE pg_catalog."default",
    material_type character varying COLLATE pg_catalog."default" NOT NULL,
    weight double precision NOT NULL,
    quantity integer NOT NULL,
    supplier_name character varying COLLATE pg_catalog."default" NOT NULL,
    cost double precision,
    received_at timestamp without time zone DEFAULT now(),
    CONSTRAINT stitching_material_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.employee_department
    ADD CONSTRAINT employee_department_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_department
    ADD CONSTRAINT employee_department_employee_id_fkey FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.paper_rolls
    ADD CONSTRAINT paper_rolls_raw_id_fkey FOREIGN KEY (raw_id)
    REFERENCES public.raw_material (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.router_access
    ADD CONSTRAINT router_access_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
